pygments: true
analytics-id: UA-44039396-3
author: Muflone
defaults:
  - scope:
      path: bluewho
    values:
      layout: bluewho
      language: english
  - scope:
      path: bluewho/italian
    values:
      language: italian
  - scope:
      path: contacts/english
    values:
      layout: contacts
      language: english
  - scope:
      path: contacts/italian
    values:
      layout: contacts
      language: italian
  - scope:
      path: cpucompare
    values:
      layout: cpucompare
      language: english
  - scope:
      path: cpucompare/italian
    values:
      language: italian
  - scope:
      path: gespeaker
    values:
      layout: gespeaker
      language: english
  - scope:
      path: gespeaker/italian
    values:
      language: italian
  - scope:
      path: gextractwinicons
    values:
      layout: gextractwinicons
      language: english
  - scope:
      path: gextractwinicons/italian
    values:
      language: italian
  - scope:
      path: gptrace
    values:
      layout: gptrace
      language: english
  - scope:
      path: gptrace/italian
    values:
      language: italian
  - scope:
      path: gwakeonlan
    values:
      layout: gwakeonlan
      language: english
  - scope:
      path: gwakeonlan/italian
    values:
      language: italian
  - scope:
      path: remmina-plugin-builder
    values:
      layout: remmina-plugin-builder
      language: english
  - scope:
      path: remmina-plugin-builder/italian
    values:
      language: italian
  - scope:
      path: remmina-plugin-exec
    values:
      layout: remmina-plugin-exec
      language: english
  - scope:
      path: remmina-plugin-exec/italian
    values:
      language: italian
  - scope:
      path: remmina-plugin-folder
    values:
      layout: remmina-plugin-folder
      language: english
  - scope:
      path: remmina-plugin-folder/italian
    values:
      language: italian
