pygments: true
analytics-id: UA-44039396-3
author: Muflone
defaults:
  - scope:
      path: bluewho
    values:
      layout: bluewho
      language: english
  - scope:
      path: bluewho/italian
    values:
      language: italian
  - scope:
      path: contacts/english
    values:
      layout: contacts
      language: english
  - scope:
      path: contacts/italian
    values:
      layout: contacts
      language: italian
  - scope:
      path: cpucompare
    values:
      layout: cpucompare
      language: english
  - scope:
      path: cpucompare/italian
    values:
      language: italian
  - scope:
      path: gespeaker
    values:
      layout: gespeaker
      language: english
  - scope:
      path: gespeaker/italian
    values:
      language: italian
