analytics-id: UA-44039396-3
author: Muflone
author_email: webreg@vbsimple.net
username_twitter: il_muflone
username_disqus: muflone
username_analytics: muflone.com
url: http://www.muflone.com
permalink: /articles/:categories/:year-:month-:day/:title.html
show_social: true
icon_footer: android-icon-48x48.png
collections:
  bluewho:
    output: true
  cpucompare:
    output: true
  gextractwinicons:
    output: true
  gnome-appfolders-manager:
    output: true
  gptrace:
    output: true
  gwakeonlan:
    output: true
  gespeaker:
    output: true
  remmina-plugin-builder:
    output: true
  remmina-plugin-exec:
    output: true
  remmina-plugin-folder:
    output: true
  remmina-plugin-open:
    output: true
  remmina-plugin-rdesktop:
    output: true
  remmina-plugin-teamviewer:
    output: true
  remmina-plugin-ultravnc:
    output: true
  remmina-plugin-url:
    output: true
defaults:
  - scope:
      path: ""
    values:
      depth: 1
      layout: articles
      require_jquery: False
      require_jquery_jplayer: False
      require_jquery_iontabs: False
  - scope:
      path: "italian/updates"
      type: "posts"
    values:
      permalink: /articles/italian/updates/:year-:month-:day.html
      tags:
        - archlinux
        - updates
  - scope:
      path: "english/updates"
      type: "posts"
    values:
      permalink: /articles/english/updates/:year-:month-:day.html
      tags:
        - archlinux
        - updates

  - scope:
      path: _bluewho
    values:
      product: bluewho
      language: english
  - scope:
      path: _bluewho/italian
    values:
      language: italian

  - scope:
      path: contacts/english
    values:
      layout: contacts
      language: english
  - scope:
      path: contacts/italian
    values:
      layout: contacts
      language: italian

  - scope:
      path: _cpucompare
    values:
      product: cpucompare
      language: english
  - scope:
      path: _cpucompare/italian
    values:
      language: italian

  - scope:
      path: _gespeaker
    values:
      product: gespeaker
      language: english
  - scope:
      path: _gespeaker/italian
    values:
      language: italian

  - scope:
      path: _gextractwinicons
    values:
      product: gextractwinicons
      language: english
  - scope:
      path: _gextractwinicons/italian
    values:
      language: italian

  - scope:
      path: _gptrace
    values:
      product: gptrace
      language: english
  - scope:
      path: _gptrace/italian
    values:
      language: italian

  - scope:
      path: _gnome-appfolders-manager
    values:
      product: gnome-appfolders-manager
      language: english
  - scope:
      path: _gnome-appfolders-manager/italian
    values:
      language: italian

  - scope:
      path: _gwakeonlan
    values:
      product: gwakeonlan
      language: english
  - scope:
      path: _gwakeonlan/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-builder
    values:
      product: remmina-plugin-builder
      language: english
  - scope:
      path: _remmina-plugin-builder/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-exec
    values:
      product: remmina-plugin-exec
      language: english
  - scope:
      path: _remmina-plugin-exec/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-folder
    values:
      product: remmina-plugin-folder
      language: english
  - scope:
      path: _remmina-plugin-folder/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-open
    values:
      product: remmina-plugin-open
      language: english
  - scope:
      path: _remmina-plugin-open/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-rdesktop
    values:
      product: remmina-plugin-rdesktop
      language: english
  - scope:
      path: _remmina-plugin-rdesktop/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-teamviewer
    values:
      product: remmina-plugin-teamviewer
      language: english
  - scope:
      path: _remmina-plugin-teamviewer/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-ultravnc
    values:
      product: remmina-plugin-ultravnc
      language: english
  - scope:
      path: _remmina-plugin-ultravnc/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-url
    values:
      product: remmina-plugin-url
      language: english
  - scope:
      path: _remmina-plugin-url/italian
    values:
      language: italian

  - scope:
      path: remmina-plugin-webkit
    values:
      layout: remmina-plugin-webkit
      language: english
  - scope:
      path: remmina-plugin-webkit/italian
    values:
      language: italian

  - scope:
      path: gtransmemory
    values:
      layout: gtransmemory
      language: english
  - scope:
      path: gtransmemory/italian
    values:
      language: italian
