analytics-id: UA-44039396-3
author: Muflone
author_email: muflone@muflone.com
username_twitter: il_muflone
username_disqus: muflone
username_analytics: muflone.com
url: http://www.muflone.com
show_social: false
icon_footer: apple-icon-60x60.png
icon_home_1: apple-icon-120x120.png
icon_home_2: android-icon-192x192.png
sections:
  - contacts
  - articles
  - gespeaker
  - gwakeonlan
  - gextractwinicons
  - bluewho
  - cpucompare
  - gptrace
  - gnome-appfolders-manager
  - gtransmemory
  - remmina-plugin-builder
  - remmina-plugin-exec
  - remmina-plugin-folder
  - remmina-plugin-open
  - remmina-plugin-rdesktop
  - remmina-plugin-rustdesk
  - remmina-plugin-teamviewer
  - remmina-plugin-ultravnc
  - remmina-plugin-url
  - remmina-plugin-webkit
  - awaitable
  - pixelcolor
  - django-admin-settings
collections:
  contacts:
    output: true
    permalink: /:collection/:path:output_ext
  articles:
    output: true
    permalink: /:collection/:path:output_ext
  bluewho:
    output: true
    permalink: /:collection/:path:output_ext
  cpucompare:
    output: true
    permalink: /:collection/:path:output_ext
  gextractwinicons:
    output: true
    permalink: /:collection/:path:output_ext
  gnome-appfolders-manager:
    output: true
    permalink: /:collection/:path:output_ext
  gptrace:
    output: true
    permalink: /:collection/:path:output_ext
  gwakeonlan:
    output: true
    permalink: /:collection/:path:output_ext
  gespeaker:
    output: true
    permalink: /:collection/:path:output_ext
  gtransmemory:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-builder:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-exec:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-folder:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-open:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-rdesktop:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-rustdesk:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-teamviewer:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-ultravnc:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-url:
    output: true
    permalink: /:collection/:path:output_ext
  remmina-plugin-webkit:
    output: true
    permalink: /:collection/:path:output_ext
  awaitable:
    output: true
    permalink: /:collection/:path:output_ext
  pixelcolor:
    output: true
    permalink: /:collection/:path:output_ext
  django-admin-settings:
    output: true
    permalink: /:collection/:path:output_ext
defaults:
  - scope:
      path: ""
    values:
      depth: 1
      layout: articles
      require_jquery_jplayer: False
      require_jquery_iontabs: False

  - scope:
      path: _articles
    values:
      product: articles
      language: english
      show_index: true
      permalink: /:collection/:categories/:slug:output_ext
  - scope:
      path: _articles/english
    values:
      language: english
      categories:
      - english
  - scope:
      path: _articles/english/jekyll
    values:
      categories:
      - english
      - jekyll
  - scope:
      path: _articles/english/arch-linux
    values:
      categories:
      - english
      - arch-linux
      show_index: false
  - scope:
      path: _articles/italian
    values:
      language: italian
      categories:
      - italian
  - scope:
      path: _articles/italian/jekyll
    values:
      categories:
      - italian
      - jekyll
  - scope:
      path: _articles/italian/arch-g50-70
    values:
      categories:
      - italian
      - installare-arch-linux-su-lenovo-g50-70
  - scope:
      path: _articles/italian/arch-linux
    values:
      categories:
      - italian
      - arch-linux
      show_index: false
  - scope:
      path: _articles/italian/zabbix
    values:
      categories:
      - italian
      - zabbix

  - scope:
      path: _contacts
    values:
      product: contacts
      language: english
  - scope:
      path: _contacts/italian
    values:
      language: italian

  - scope:
      path: _bluewho
    values:
      product: bluewho
      language: english
  - scope:
      path: _bluewho/italian
    values:
      language: italian

  - scope:
      path: _cpucompare
    values:
      product: cpucompare
      language: english
  - scope:
      path: _cpucompare/italian
    values:
      language: italian

  - scope:
      path: _gespeaker
    values:
      product: gespeaker
      language: english
  - scope:
      path: _gespeaker/italian
    values:
      language: italian

  - scope:
      path: _gextractwinicons
    values:
      product: gextractwinicons
      language: english
  - scope:
      path: _gextractwinicons/italian
    values:
      language: italian

  - scope:
      path: _gptrace
    values:
      product: gptrace
      language: english
  - scope:
      path: _gptrace/italian
    values:
      language: italian

  - scope:
      path: _gnome-appfolders-manager
    values:
      product: gnome-appfolders-manager
      language: english
  - scope:
      path: _gnome-appfolders-manager/italian
    values:
      language: italian

  - scope:
      path: _gwakeonlan
    values:
      product: gwakeonlan
      language: english
  - scope:
      path: _gwakeonlan/italian
    values:
      language: italian

  - scope:
      path: _gtransmemory
    values:
      product: gtransmemory
      language: english
  - scope:
      path: _gtransmemory/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-builder
    values:
      product: remmina-plugin-builder
      language: english
  - scope:
      path: _remmina-plugin-builder/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-exec
    values:
      product: remmina-plugin-exec
      language: english
  - scope:
      path: _remmina-plugin-exec/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-folder
    values:
      product: remmina-plugin-folder
      language: english
  - scope:
      path: _remmina-plugin-folder/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-open
    values:
      product: remmina-plugin-open
      language: english
  - scope:
      path: _remmina-plugin-open/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-rdesktop
    values:
      product: remmina-plugin-rdesktop
      language: english
  - scope:
      path: _remmina-plugin-rdesktop/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-rustdesk
    values:
      product: remmina-plugin-rustdesk
      language: english
  - scope:
      path: _remmina-plugin-rustdesk/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-teamviewer
    values:
      product: remmina-plugin-teamviewer
      language: english
  - scope:
      path: _remmina-plugin-teamviewer/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-ultravnc
    values:
      product: remmina-plugin-ultravnc
      language: english
  - scope:
      path: _remmina-plugin-ultravnc/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-url
    values:
      product: remmina-plugin-url
      language: english
  - scope:
      path: _remmina-plugin-url/italian
    values:
      language: italian

  - scope:
      path: _remmina-plugin-webkit
    values:
      product: remmina-plugin-webkit
      language: english
  - scope:
      path: _remmina-plugin-webkit/italian
    values:
      language: italian

  - scope:
      path: _awaitable
    values:
      product: awaitable
      language: english
  - scope:
      path: _awaitable/italian
    values:
      language: italian

  - scope:
      path: _pixelcolor
    values:
      product: pixelcolor
      language: english
  - scope:
      path: _pixelcolor/italian
    values:
      language: italian

  - scope:
      path: _django-admin-settings
    values:
      product: django-admin-settings
      language: english
  - scope:
      path: _django-admin-settings/italian
    values:
      language: italian
