pygments: true
analytics-id: UA-44039396-3
author: Muflone
defaults:
  - scope:
      path: bluewho
    values:
      layout: bluewho
      language: english
  - scope:
      path: bluewho/italian
    values:
      language: italian
  - scope:
      path: contacts/english
    values:
      layout: contacts
      language: english
  - scope:
      path: contacts/italian
    values:
      layout: contacts
      language: italian
