<div class="big center"><a href="/articles">Everything</a>
  <a href="/articles/feed.xml"><img src="/resources/index/24-rss.png"></a> | 
  <a href="/articles/english">English language</a>
  <a href="/articles/english/feed.xml"><img src="/resources/index/24-rss.png"></a> | 
  <a href="/articles/italian">Italian language</a>
  <a href="/articles/italian/feed.xml"><img src="/resources/index/24-rss.png"></a> | 
  <br />&nbsp;</div>